#ifndef __BRepPrincipalFrame__
#define __BRepPrincipalFrame__

/**
@file
Subclass of PrincipalFrame, which is generated by wxFormBuilder.
*/

#include "PrincipalFrame.h"
#include "wx/wx.h"

/** Implementing PrincipalFrame */
class BRepPrincipalFrame : public PrincipalFrame
{
protected:
	// Handlers for PrincipalFrame events.
	void newModel( wxCommandEvent& event );
	void quit( wxCommandEvent& event );
	void about( wxCommandEvent& event );
	void openModel( wxCommandEvent& event );
	void saveModel( wxCommandEvent& event );
	void zoomIn( wxCommandEvent& event );
	void zoomOut( wxCommandEvent& event );

public:
	/** Constructor */
	BRepPrincipalFrame( wxWindow* parent );

    void init();
};

#endif // __BRepPrincipalFrame__
