#ifndef __BRepEdit_Dialog__
#define __BRepEdit_Dialog__

/**
@file
Subclass of Edit_Dialog, which is generated by wxFormBuilder.
*/

#include "Edit_Dialog.h"
#include "wx/msgdlg.h"

/** Implementing Edit_Dialog */
class BRepEdit_Dialog : public Edit_Dialog
{
private:
    double posX;
    double posY;
    double posZ;
protected:
	// Handlers for Edit_Dialog events.
	void sendData( wxCommandEvent& event );

public:
	/** Constructor */
	BRepEdit_Dialog( wxWindow* parent );
	float getX();
	float getY();
    float getZ();
};

#endif // __BRepEdit_Dialog__
