#ifndef __BRepRotate_Dialog__
#define __BRepRotate_Dialog__

/**
@file
Subclass of Rotate_Dialog, which is generated by wxFormBuilder.
*/

#include "Rotate_Dialog.h"
#include "wx/msgdlg.h"

/** Implementing Rotate_Dialog */
class BRepRotate_Dialog : public Rotate_Dialog
{
private:
    double posX;
    double posY;
    double posZ;
    double angle;

protected:
	// Handlers for Rotate_Dialog events.
	void sendData( wxCommandEvent& event );

public:
	/** Constructor */
	BRepRotate_Dialog( wxWindow* parent );
	float getX();
	float getY();
    float getZ();
    float getAngle();
};

#endif // __BRepRotate_Dialog__
