#ifndef __BRepSweeping_Dialog__
#define __BRepSweeping_Dialog__

/**
@file
Subclass of Sweeping_Dialog, which is generated by wxFormBuilder.
*/

#include "Sweeping_Dialog.h"
#include "wx/msgdlg.h"

/** Implementing Sweeping_Dialog */
class BRepSweeping_Dialog : public Sweeping_Dialog
{
private:
        double posX;
        double posY;
        double posZ;
protected:
	// Handlers for Sweeping_Dialog events.
	void sweeping( wxCommandEvent& event );

public:
	/** Constructor */
	BRepSweeping_Dialog( wxWindow* parent );
	float getX();
	float getY();
	float getZ();
};

#endif // __BRepSweeping_Dialog__
